# hub-stage: publish
name: Publish

on:
  push:
    tags:
      - 'test-cypress@*'

permissions:
  contents: read
  packages: write

concurrency:
  group: publish-github-packages
  cancel-in-progress: false

jobs:
  publish-cy-platform:
    if: startsWith(github.ref_name, 'cy-platform@')
    uses: ExperienceQuality/.github/.github/workflows/node-library-publish.yml@v1
    with:
      node-version: '24'
      package-manager: npm
      package-name: '@xq/test-cypress'
      package-directory: packages/test-cypress
      tag-prefix: test-cypress
